# Generated by Django 5.2 on 2025-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
